/**
 * This is the full Specimen interface, complete with the necessary information
 * to filter the specimen dataset via the label form, as well as construct labels.
 */
export interface SpecimenLabel {
    order: string,
    family: string,
    subfamily: string,
    tribe: string,
    genus: string,
    species: string,
    subspecies: string,
    taxon: {
        name: string,
        trinomial?: string,
        binomial?: string,
        common_name: string,
        authority: string
    }
    determiner_firstname: string,
    determiner_lastname: string,
    determiner_year: number,
    usi: string,
    preparer_firstname: string,
    preparer_lastname: string,
    preparation: string,
    preparation_date: string,
    sex: string,
    stage: string,
    labels_printed: boolean,
    labeled: boolean,
    photographed: boolean,
    identified: boolean,
    country: string,
    country_abbr: string,
    state: string,
    state_abbr: string,
    county: string,
    county_abbr: string,
    county_full_name: string,
    locality: string,
    locality_range: string,
    locality_town: string,
    gps_lat: string,
    gps_long: string,
    elevation: string,
    elevation_meters: string,
    collecting_trip: string,
    day: number,
    month: string,
    year: number,
    collected_date: string,
    collector_firstname: string,
    collector_lastname: string,
    collectors: string,
    method: string,
    weather: string,
    temperature: string,
    temp_F: string,
    temp_C: string,
    time_of_day: string,
    habitat: string,
    notes: string
}
